name: "Autotests with Playwright"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  pw-autotests:
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.56.1-jammy
    steps:
      - name: "Checkout project repository"
        uses: actions/checkout@v4
      - name: "Install node js"
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: "Install project dependecies"
        run: npm ci
      - name: "Run tests"
        run: npm test
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
          HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
          USER_CREDENTIALS_EMAIL: ${{secrets.USER_CREDENTIALS_EMAIL}}
          USER_CREDENTIALS_PASSWORD: ${{secrets.USER_CREDENTIALS_PASSWORD}}
      - name: "Upload tests report to artifacts"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: playwright-report/
          retention-days: 4